name: Build and Push to ECR

on:
  push:
    branches: ["main"]
    paths:
      - "**"
  pull_request:
    branches: ["main"]
    paths:
      - "**"

env:
  AWS_REGION: eu-central-1

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Debug Information
        run: |
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "Working Directory: ${{ github.workspace }}"
          ls -la
          pwd

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug After Checkout
        run: |
          echo "Repository contents:"
          ls -la
          echo "Dockerfile location:"
          find . -name "Dockerfile"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
